# Generated by Django 3.2.9 on 2022-01-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220112_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdashboardmodule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
