# Generated by Django 3.2.16 on 2022-12-24 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BsubCreatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('subscene_url', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='submaker_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('tmdb_thumbnail', models.URLField(blank=True, max_length=999, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('episode', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link_main_source', models.URLField(blank=True, max_length=999, null=True)),
                ('watch_link_alt1_name', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link_alt1_url', models.URLField(blank=True, max_length=999, null=True)),
                ('watch_link_alt2_name', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link_alt2_url', models.URLField(blank=True, max_length=999, null=True)),
                ('subtitle_link', models.URLField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('season',),
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='LinkEpisodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('tmdbid', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('tmdb_poster', models.URLField(blank=True, max_length=999, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('tmdb_thumbnail', models.URLField(blank=True, max_length=999, null=True)),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('writers', models.CharField(blank=True, max_length=250, null=True)),
                ('starring', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('bengali', 'Bengali'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('documentary', 'Documentary'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True)),
                ('runtime', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=999, null=True)),
                ('watch_link_main_source', models.URLField(blank=True, max_length=999, null=True)),
                ('watch_link_alt1_name', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link_alt1_url', models.URLField(blank=True, max_length=999, null=True)),
                ('watch_link_alt2_name', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link_alt2_url', models.URLField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('synopsys', models.TextField(blank=True, null=True)),
                ('subtitle_link', models.URLField(blank=True, max_length=999, null=True)),
                ('still_path', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bsub_creator', models.ManyToManyField(blank=True, to='app_main.BsubCreatorModel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(max_length=250, to='app_main.GenreModel')),
                ('last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbid', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tmdb_poster', models.URLField(blank=True, max_length=999, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('tmdb_thumbnail', models.URLField(blank=True, max_length=999, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('writers', models.CharField(blank=True, max_length=250, null=True)),
                ('starring', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('bengali', 'Bengali'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('documentary', 'Documentary'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('synopsys', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bsub_creator', models.ManyToManyField(blank=True, to='app_main.BsubCreatorModel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user_series', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, max_length=250, to='app_main.GenreModel')),
                ('last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_user_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TopSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
                ('series_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.seriesmodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SuperheroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwaresGamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(blank=True, choices=[('softwares', 'Softwares'), ('games', 'Games'), ('ebooks', 'eBooks'), ('tutorials', 'Tutorials')], default='Games', max_length=50, null=True)),
                ('platform', models.CharField(blank=True, choices=[('pc', 'PC'), ('android', 'Android'), ('console', 'Console')], default='PC', max_length=50, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('developer', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_sys_req', models.TextField(blank=True, null=True)),
                ('rec_sys_req', models.TextField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('direct_download', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('torrent', models.URLField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user_sge', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, max_length=250, to='app_main.GenreModel')),
                ('last_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_user_sge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('season_number', models.IntegerField(blank=True, default=0, null=True)),
                ('episode_count', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('download_full_quality_480p', models.URLField(blank=True, max_length=999, null=True)),
                ('download_full_quality_720p', models.URLField(blank=True, max_length=999, null=True)),
                ('download_full_quality_1080p', models.URLField(blank=True, max_length=999, null=True)),
                ('download_full_quality_2160p', models.URLField(blank=True, max_length=999, null=True)),
                ('download_full_download_dual_audio', models.URLField(blank=True, max_length=999, null=True)),
                ('download_full_download_hindi_dubbed', models.URLField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.seriesmodel')),
            ],
            options={
                'ordering': ('series__title', 'season_number'),
            },
        ),
        migrations.CreateModel(
            name='SatyajitRayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OscarWinningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LinkSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksubcat', to='app_main.linkcategory')),
            ],
            options={
                'ordering': ('subcategory',),
            },
        ),
        migrations.CreateModel(
            name='LinkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksource', to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('source',),
            },
        ),
        migrations.CreateModel(
            name='LinkEpisodeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodesubcat', to='app_main.linkepisodecategory')),
            ],
            options={
                'ordering': ('subcategory',),
            },
        ),
        migrations.CreateModel(
            name='LinkEpisodeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodesource', to='app_main.episodemodel')),
            ],
            options={
                'ordering': ('source',),
            },
        ),
        migrations.AddField(
            model_name='linkepisodecategory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodecat', to='app_main.linkepisodesource'),
        ),
        migrations.AddField(
            model_name='linkcategory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkcat', to='app_main.linksource'),
        ),
        migrations.CreateModel(
            name='JamesBondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IMDBTopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HindiDubbedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FootageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_main.seasonmodel'),
        ),
        migrations.CreateModel(
            name='DualAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('horror', 'Horror'), ('foreign', 'Foreign')], default='hollywood', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_main.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
