# Generated by Django 3.2.16 on 2023-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsubcreatormodel',
            name='subscene_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='linksubcategory',
            name='link',
            field=models.URLField(max_length=9999, null=True),
        ),
    ]
