# Generated by Django 3.2.16 on 2023-01-20 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20230120_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksubcategory',
            name='link',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
